### ISSUE TITLE
Bulding on freshly installed ubuntu

### ISSUE THREAD

**Issue by padok** [JARVIS-MoCap/JARVIS-AcquisitionTool#1]
Hey,

I added this to the beginning my cmake file:
```cmake
set(UBUNTU_VERSION "2004")
```
since it was not set by my system, and I'm currently trying to build the project.

I also installed this version of spinnaker: https://flir.app.boxcn.net/v/SpinnakerSDK/file/941078493472
-> spinnaker-2.6.0.157-Ubuntu20.04-amd64-pkg.tar.gz

And it builds, but when I try to run it, I get this shared library error.
```
/home/smg/git/JARVIS-AcquisitionTool/build/AcquisitionTool: error while loading shared libraries: libGenApi_gcc540_v3_0.so: cannot open shared object file: No such file or directory
```

From what I cat tell its a file that gets installed alongside Spinnaker, and it is present in `/opt/spinnaker/lib/libGenApi_gcc9_v3_0.so` which is added to the system path by `/etc/ld.so.conf.d/libspinnaker.conf`

Did you had this kind of error before?

Additionally, is there a particular reason why spinnaker is included like this in the repo?

**Comment by JARVIS-MoCap** [comment]
Hi,

If you're using Ubuntu 2004/1804 you need to manually specify which version you are using. Either by setting it in the CMake file like you did, or by adding `-DUBUNTU_VERSION=xx04` (replace xx by 20 or 18) to your cmake command. I admit this is a bit clunky and I'll try to find a better solution in the future.

I had some issues with the default install of the spinnaker libraries some time ago, which caused me to switch to shipping them with the repository. I'll see if those issues are solved using the recent version of the libraries and remove the included version if that's the case.

Thanks a lot for the feedback!
