### ISSUE TITLE
Difficulty installing Jarvis Toolbox

### ISSUE THREAD

**Issue by olinesn** [JARVIS-MoCap/JARVIS-AcquisitionTool#16]
Hello,

I'm following the installation guide on a Windows 11 PC, and I'm sure I'm missing something simple, however I'm getting stuck. May I please ask for help?

I'm following this guide: https://jarvis-mocap.github.io/jarvis-docs/getting_started/2_exploring_example/

Step 1: The git clone command in Anaconda Powershell is breaking for me. 

> (base) PS C:\Users\soline> git clone https://github.com/JARVIS-MoCap/JARVIS-HybridNet.git && cd JARVIS-HybridNet
> At line:1 char:64
> + ... clone https://github.com/JARVIS-MoCap/JARVIS-HybridNet.git && cd JARV ...
> +                                                                ~~
> The token '&&' is not a valid statement separator in this version.
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : InvalidEndOfLine
> 
> (base) PS C:\Users\soline>

Step 1 (Alternate): I downloaded the .zip file in the link into my Downloads folder, and unzipped the file.

Step 2a: Create the jarvis Anaconda environment by running:
conda create -n jarvis python=3.9  pytorch=1.10.1 torchvision cudatoolkit=11.3 notebook  -c pytorch
[completed]
Step 2b: Activate the environment (you will need to do this every time you open a terminal to use JARVIS):
[completed]
Step 2c: conda activate jarvis
[completed]
Step2d: Install the required version of the setuptools package:
pip install -U setuptools==59.5.0
[completed]
Step2e: Install JARVIS:
pip install -e .
[Breaks here]

> (jarvis) PS C:\Users\soline> pip install -e .
> Obtaining file:///C:/Users/soline
> ERROR: file:///C:/Users/soline does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
> (jarvis) PS C:\Users\soline>

I have a feeling that this may have something to do with attaching the downloaded, unzipped folder to Anaconda, but I don't have the foundation to proceed. May I please ask for help?

Thanks so much!

**Comment by JARVIS-MoCap** [comment]
Hi,

I think the Powershell does not support concatenating commands using  '&&'. In you case you can just call `git clone https://github.com/JARVIS-MoCap/JARVIS-HybridNet.git` and `cd JARVIS-HybridNet` separately. 

Let me know if you have any other issues!

**Comment by olinesn** [comment]
Thank you for this help, I really appreciate your time! Maybe it makes sense to update the documentation - I know that they are low-level steps, but would still be helpful for newer users.

**Comment by JARVIS-MoCap** [comment]
That's a good point, I'll make sure that the tutorial can be followed without any modifications on all operating system!

Thanks again for pointing this out. I'll close the issue for now, but feel free to reopen it if you run into another similar issue.
